spring:
  application:
    name: ZipkinService
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0


server:
  port: 7000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/

