zuul:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    ServiceProvider:
      path: /ServiceProvider/**
      serviceId: ServiceProvider
    RegistrationCenter:
      path: /RegistrationCenter/**
      serviceId: blog-service
    MercenaryAccount:
      path: /MercenaryAccount/**
      serviceId: MercenaryAccount
    ConfigServer:
      path: /ConfigServer/**
      serviceId: ConfigServer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/

server:
  port: 5000
Spring:
  application:
    name: GatewayService


